# DataFrame
- Series 가 1차원이었따면 DataFrame은 2차원으로 확대된 버전이다.
- Excel의 SpreadSheet라고 생각하면 이해하기 쉽다.
- 2차원이기떄문에 인덱스가 row, coulm으로 구성되어있다.
      - row: 각 개별 데이터
      - coulum: 각 개별 속성을 의미
- Data Analysis, Machine Learning에 Data를 변경하기 위해서 많이 사용된다.

https://petvibelabs.com/dog-mbti-test.html

In [3]:
 import os
import numpy as np
import pandas as pd

base_path = r"C:\kdt_0900_lsu\data_analysis\resource\dataset"
file_name = r"titanic.csv"

file_path = os.path.join(base_path, file_name)

In [5]:
pd.read_csv(file_path).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 컬럼의 의미
    - survival: Survival(0 = no; 1 = yes)
    - class: Passenger Class(1 = 1st, 2 = 2nd, 3 = 3rd)
    - name: Name #이름
    - sex: Sex #성별
    - age: Age #나이
    - sibsp: Number of Siblings/Spouses Aboard #동승 형제
    - parch: Number of Parents/Children Aboard #동승 부모,자식
    - ticket: Ticket Number #티켓 번호
    - fare: Passenger Fare
    - cabin: Cabin # 객실번호
    - embarked - Pork of Embarkation(C = Cherbourg; Q = Queenstown, S = Southampthon) # 탑승장소

1단계 데이터 파악
- shape: 속성(row, coulum)
- describe: 통계치 계산 함수(기술통계랑) -> 정수형의 데이터만 볼 수 았음( 성별같은 문자열 데이터는 안됨)
- info: 데이터의 타입, 각 컬럼의 개수 출력

In [7]:
titanic_df = pd.read_csv(file_path)

In [9]:
print(titanic_df.shape)   # 숫자가 두개라 이차원 (행:891개, 속성:12개)

(891, 12)

In [12]:
#기술통계랑

titanic_df.describe() #기술통계랑

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [15]:
print(titanic_df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [17]:
len(titanic_df)

891

In [18]:
print(titanic_df.size)

10692

In [19]:
print(titanic_df.ndim)

2

In [20]:
titanic_df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

## dict -> DataFrame (딕셔너리를 가지고 데이터 프레임 만들깅)

In [25]:
data = {"이름": "홍길동", "나이":20, "주소": "서울시 강남"}
data

# dict 2차원인 indax값을 같이 제공해야한다
pd.DataFrame(data, index=[0, 1, 2])

    이름  나이      주소
0  홍길동  20  서울시 강남
1  홍길동  20  서울시 강남
2  홍길동  20  서울시 강남

In [31]:
data2 = {"이름": ["럭키","초이","까미"],"나이":[15, 12, 14], "주소": ["서울시 강남구","서울시 종로구","서울시 노원구"]}


pd.DataFrame(data2, index=[0, 1, 2])

   이름  나이       주소
0  럭키  15  서울시 강남구
1  초이  12  서울시 종로구
2  까미  14  서울시 노원구

In [33]:
#시리즈도 판다스(값)을 만들 수 있을까 ? -> 시리즈들이 모이면 데이터프레임이됨

a = pd.Series(data=["망곰이", 23, "서울시 노원"], index=["이름","나이","주소"])
b = pd.Series(data=["마루", 22, "서울시 의정부"], index=["이름","나이","주소"])
c = pd.Series(data=["콩", 24, "서울시 동대문구"], index=["이름","나이","주소"])

pd.DataFrame([a, b, c])

    이름  나이        주소
0  망곰이  23    서울시 노원
1   마루  22   서울시 의정부
2    콩  24  서울시 동대문구

## 데이터 프레임의 인덱싱

In [36]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [38]:
titanic_df["Name"]    # -> 시리즈 타입 (판다스를 하나 들르고오면 시리즈 타입)

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

## 단일 컬럼 슬라이싱

In [47]:
# 데이터프레임으로 슬라이싱

print(type(titanic_df[["Name"]]))
titanic_df[["Name"]]

<class 'pandas.core.frame.DataFrame'>

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

## 복수 컬럼 슬라이싱

In [46]:
# 인덱싱으로 가져오려면 두개만 가져오면 안된다-> 대괄호를 두번감싸서 해당 컬럼 들을 선택해서 가져올 수 있당

titanic_df[["Name","Age"]].head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [49]:
# titanic_df[["Survived":"Age"]] -> 이런식으로 가져오면되고 low의 인덱스의 번호부터 슬라이싱 가능해 예를 들어 행에 대한 슬라이싱이면 [0:3]

## Data Frame 행 슬라이싱

In [51]:
titanic_df[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [53]:
# step 기능, indexing 가능
titanic_df[::10].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S

## loc, iloc: row 선택

In [54]:
titanic_df.loc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [57]:
print(type(titanic_df.loc[3]))


titanic_df.loc[3]

<class 'pandas.core.series.Series'>

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [55]:
titanic_df.iloc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [62]:
# 데이터가 결측값이 있을때 차이가 있음 예를들어 데이터들의 번호가 지금은 1번부터 차례로 올라가지만 데이터를 재 가공해서 중간에 띄어므띠엄 데이터가 존재할경우 
# loc: 데이터가 비어지고 난 다음에 다시 차례로 인덱스를 부여
# iloc: 중간에 결측값이 생겨도 초기의 인덱스 값으로 불러옴

In [63]:
# 1이라고 적으면 데이터가 가지고 있는 고유한 번호 1을 찾기에 데이터가 없다고 뜸 -> 1출력 불가

titanic_df[::10].loc[1]

KeyError: 1

In [64]:
# 데이터의 시각적인 번호가아니라 현재 있는 데이터들을 기준으로 고유한 인덱스 번호를 붙임 -> 1출력 가능

titanic_df[::10].iloc[1]

PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Ticket                                 PP 9549
Fare                                      16.7
Cabin                                       G6
Embarked                                     S
Name: 10, dtype: object

## 다중 행 선택 (인덱스)

In [66]:
# 현재는 결측치가 없어서 둘중(loc, iloc) 뭘 사용해도 결과가 같다

In [65]:
titanic_df.loc[[1, 600, 800]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
600,601,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.0,2,1,243847,27.0000,NaN,S
800,801,0,2,"Ponesell, Mr. Martin",male,34.0,0,0,250647,13.0000,NaN,S

In [69]:
titanic_df[:3]      # 3을 포함하지 않음

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [70]:
titanic_df.loc[:3]     # 3을 포함

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [ ]:
titanic_df.iloc[-1]

In [72]:
titanic_df.loc[1,"Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [73]:
# titanic_df.loc[-1]
titanic_df.iloc[-1]

PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

In [83]:
# 100행 데이터의 나이

titanic_df.loc[100, "Age"]
titanic_df.loc[[100]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [88]:
# 100행 데이터의 나이

print(titanic_df[::5].loc[100, "Age"])
titanic_df[::5].loc[[100]]

28.0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [92]:
# 100행 데이터의 나이

print(titanic_df[::5].iloc[100]["Age"])
titanic_df[::5].iloc[[100]]

17.0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
500,501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,NaN,S

In [93]:
titanic_df.loc[[100,200,300], ["Name","Age"]]

                                         Name   Age
100                   Petranec, Miss. Matilda  28.0
200            Vande Walle, Mr. Nestor Cyriel  28.0
300  Kelly, Miss. Anna Katherine "Annie Kate"   NaN

In [94]:
titanic_df.loc[[100,200,300]][["Name","Age"]]

                                         Name   Age
100                   Petranec, Miss. Matilda  28.0
200            Vande Walle, Mr. Nestor Cyriel  28.0
300  Kelly, Miss. Anna Katherine "Annie Kate"   NaN

## Boolean Selection

In [95]:
ask_mask = titanic_df["Age"] > 30
len(titanic_df[ask_mask])

305

In [96]:
titanic_df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [100]:
# Fare을 400달러 이상 주고 산 사람  -> 적절한 마스크는 인사이트를 얻을 수 있다 

hogu_mask = titanic_df["Fare"] > 400
titanic_df[hogu_mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

## 여성의 생존자 조회

In [119]:
survived_mask = (titanic_df["Survived"] == 1) & (titanic_df["Sex"] == "female")
survived_mask

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Length: 891, dtype: bool

In [123]:
servived_female = titanic_df[survived_mask]
servived_female.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [128]:
femail = titanic_df[titanic_df["Sex"] == "female"]
len(femail)

314

In [129]:
print(f"생존자 수: {len(servived_female)}명")
print(f"생존율: 약 {round(len(servived_female) / len(femail), 4) * 100}%")

생존자 수: 233명
생존율: 약 74.2%

In [127]:
survived_female_mask = (titanic_df["Survived"] == 1) & (titanic_df["Sex"] == "female")
titanic_df[survived_female_mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

1등석과 3등석의 생존율 비교

In [132]:
survived_mask = titanic_df["Survived"] == 1

titanic_df[survived_mask]

print(f"타이타닉호의 생존율: {len(titanic_df[survived_mask]) / len(titanic_df) * 100:.2f}%")

타이타닉호의 생존율: 38.38%

In [135]:
pclass_1_mask = titanic_df["Pclass"] == 1
pclass_3_mask = titanic_df["Pclass"] == 3

pclass_1_survived = len(titanic_df[survived_mask & pclass_1_mask])
pclass_3_survived = len(titanic_df[survived_mask & pclass_3_mask])

print(f"타이타닉호의 생존율: {pclass_1_survived / len(titanic_df[pclass_1_mask]) * 100:.2f}%")
print(f"타이타닉호의 생존율: {pclass_3_survived / len(titanic_df[pclass_3_mask]) * 100:.2f}%")

타이타닉호의 생존율: 62.96%
타이타닉호의 생존율: 24.24%

In [143]:
titanic_df.groupby("Pclass")["Survived"].agg(["mean", "count"])

            mean  count
Pclass
1       0.629630    216
2       0.472826    184
3       0.242363    491

In [144]:
survived_pclass = titanic_df.grouby("Pclass")["Survived"].mean()

print(survived_pclass)

AttributeError: 'DataFrame' object has no attribute 'grouby'

In [141]:
survived_pclass = titanic_df.groupby("Pclass")["Survived"].mean()

pd.DataFrame(data=survived_pclass * 100, index=[1, 2, 3])

    Survived
1  62.962963
2  47.282609
3  24.236253

In [142]:
survived_pclass = titanic_df.groupby("Pclass")["Survived"].mean()
survived_pclass.index = ["1등석", "2등석", "3등석"]
survived_pclass

pd.DataFrame(data=survived_pclass * 100, index=["1등석", "2등석", "3등석"])

      Survived
1등석  62.962963
2등석  47.282609
3등석  24.236253

파생 데이터
- 기존에 존재하는 속성(변수, 컬럼)으로부터 새로운 속성(컬럼)을 만들어낸 변수

In [146]:
# key가 없으면 추가
titanic_df["RealAge"] = titanic_df["Age"] -1

titanic_df

## 변수 삭제(columns 삭제): drop()
- axis=0(default)-행, 1-열
- inplace=False(default)

In [149]:
titanic_df.drop(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,RealAge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,21.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,37.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,34.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,34.0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,26.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,18.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,31.0

In [154]:
# titanic_df.drop("Cabin") -> 오류발생
# 여러개를 지울때에는 배열로 전달해서 해당값을 찾아갈 수 있게하여, 삭제해야한다 (튜플은 X)
# 원본데이터는 보통 지우지 않음, 복사본을 만들어서 수정하고 원본데이터는 유지 


titanic_df.drop("Cabin", axis=1)
titanic_df.drop(["Cabin","Embarked"], axis=1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,RealAge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,21.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,37.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,25.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,34.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,34.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,26.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,18.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,25.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,31.0

## 파생변수 만들기 연습

In [155]:
np.nan == np.nan

False

In [160]:
# 만약 NaN이라면: 알수없음
# 19세 이상: 성인
# 19세 미만: 아이
# id ~ elif ~ else

# 경우의 수가 세개니까 삼항은 사용할 수 없고 if-else가 더 유용하다. 단 선택해야할 것은 람다를 쓰게되면 삼항은 사용할 수 있는대 이프문은 사용하시 어렵다
# 이런경우 함수로 뺴놓고 작업한다

def get_adult(age):
    if np.isnan(age):
        return "알 수 없음"

    return "성인" if age >= 19 else "아이"



get_adult(np.nan)

'알 수 없음'

In [162]:
def get_adult(age):
    if np.isnan(age):
        return "알 수 없음"

    return "성인" if age >= 19 else "아이"



get_adult(10)

'아이'

In [163]:
def get_adult(age):
    if np.isnan(age):
        return "알 수 없음"

    return "성인" if age >= 19 else "아이"



get_adult(20)

'성인'

In [161]:
bool(np.isnan(10))

False

In [168]:
# apply(): 앞의 시리즈의 값을 순차적으로 받아서 결과를 바꾸고 새로운 결과를 반환하는 함수

titanic_df["IsAdult"] = titanic_df["Age"].apply(get_adult)
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,RealAge,IsAdult
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,21.0,성인
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,37.0,성인
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,25.0,성인
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,34.0,성인
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,34.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,26.0,성인
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,18.0,성인
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN,알 수 없음
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.0,성인
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,31.0,성인

In [5]:
# Ripoff
# Fare > 300: 바가지 요금
# Fare <= 300: 정상요금 


titanic_df["Ripoff"] = titanic_df["Fare"].apply(lambda fare: "바가지" if fare > 300 else "정상")

NameError: name 'titanic_df' is not defined

In [3]:
titanic_df[titanic_df["Fare"] > 300]

NameError: name 'titanic_df' is not defined

In [4]:
# 파생 변수 IsAdult, RipOff 두개를 모두 삭제 

titanic_df.drop(["IsAdult","RipOdd"], axis=1, inplace=True)

NameError: name 'titanic_df' is not defined